### ISSUE TITLE
Prevent NullPointerException in EventStoreSink.updateInsertSpeedMetrics

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.eventstore#108]
could happen if multiple operator instances are running in the same PE
```
 ERROR #‌splapptrc,J[6],P[216],xxx_Ingest M[EventStoreSink.java:com.ibm.streamsx.eventstore.EventStoreSink.processBatch:1180]  - Failed to write tuple to EventStore.
java.lang.NullPointerException
        at com.ibm.streamsx.eventstore.EventStoreSink.updateInsertSpeedMetrics(EventStoreSink.java:1111)
        at com.ibm.streamsx.eventstore.EventStoreSink.processBatch(EventStoreSink.java:1169)
        at com.ibm.streamsx.eventstore.EventStoreSink$InsertRunnable.run(EventStoreSink.java:277)
        at java.lang.Thread.run(Thread.java:811)
        at com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)
```

**Comment by markheger** [comment]
* exception in this method should not cause PE restart
